version: '3'

services:
 agent_langchain:
    build: ./Langchain
    ports:
      - "5011:5011"
    networks:
      - mynetwork
 
 ui:
    build: ./UI
    ports:
      - "5010:5010"
    depends_on:
      - agent_langchain
    networks:
      - mynetwork
    stdin_open: true
    tty: true

networks:
  mynetwork:
    driver: bridge

