
version: '3'

services:
  service_a:
    build: ./service_a
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  service_b:
    build: ./service_b
    ports:
      - "5001:5001"
    depends_on:
      - service_a
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

